//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facture.IdentityAccess.Application
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SN
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SN()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Facture.IdentityAccess.Application.SN", typeof(SN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontró un software autorizado. Contrato padre: &apos;{0}&apos;, Contrato: &apos;{1}&apos;.
        /// </summary>
        public static string AuthorizedSoftwareNotFound
        {
            get
            {
                return ResourceManager.GetString("AuthorizedSoftwareNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Las credenciales ingresadas son inválidas..
        /// </summary>
        public static string BadCredentials
        {
            get
            {
                return ResourceManager.GetString("BadCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contenedor no existe en Url del blob: &apos;{0}&apos;..
        /// </summary>
        public static string BlobContainerDoesNotExist
        {
            get
            {
                return ResourceManager.GetString("BlobContainerDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Url del blob es muy corta: &apos;{0}&apos;..
        /// </summary>
        public static string BlobUriTooShort
        {
            get
            {
                return ResourceManager.GetString("BlobUriTooShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El contrato del grupo de orgien es diferente al contrato del grupo destino..
        /// </summary>
        public static string BothGroupsAreFromDifferentTenants
        {
            get
            {
                return ResourceManager.GetString("BothGroupsAreFromDifferentTenants", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contrato hijo no pertenece al contrato padre actual..
        /// </summary>
        public static string ChildDoesNotBelongToThisParent
        {
            get
            {
                return ResourceManager.GetString("ChildDoesNotBelongToThisParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default {0} administrator.
        /// </summary>
        public static string DefaultTenantAdministrator
        {
            get
            {
                return ResourceManager.GetString("DefaultTenantAdministrator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rango de fechas para Enablement es inválido..
        /// </summary>
        public static string EnablementInvalidDateRange
        {
            get
            {
                return ResourceManager.GetString("EnablementInvalidDateRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El objeto Enablement es requerido..
        /// </summary>
        public static string EnablementObjectIsRequired
        {
            get
            {
                return ResourceManager.GetString("EnablementObjectIsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se encontró un software autorizado con el mismo token de seguridad. Contrato padre: &apos;{0}&apos;, Contrato: &apos;{1}&apos;.
        /// </summary>
        public static string ExistingAuthorizedSoftware
        {
            get
            {
                return ResourceManager.GetString("ExistingAuthorizedSoftware", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ya existe un contrato registrado con este token..
        /// </summary>
        public static string ExistingToken
        {
            get
            {
                return ResourceManager.GetString("ExistingToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El contrato del grupo es diferente al contrato del registro..
        /// </summary>
        public static string GroupAndRowAreFromDifferentTenants
        {
            get
            {
                return ResourceManager.GetString("GroupAndRowAreFromDifferentTenants", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El grupo destino ya contiene el grupo origen como hijo..
        /// </summary>
        public static string GroupIsChildAndCannotBeParent
        {
            get
            {
                return ResourceManager.GetString("GroupIsChildAndCannotBeParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es incorrecta..
        /// </summary>
        public static string InvalidCredentials
        {
            get
            {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contraseña es inválida..
        /// </summary>
        public static string InvalidPassword
        {
            get
            {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extensión de teléfono es inválida..
        /// </summary>
        public static string InvalidPhoneExtension
        {
            get
            {
                return ResourceManager.GetString("InvalidPhoneExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se excedió la max. profundidad de anidamiento de grupo ({0})..
        /// </summary>
        public static string MaxRecursionDepthExceeded
        {
            get
            {
                return ResourceManager.GetString("MaxRecursionDepthExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plataforma es requerida. El contrato debería tener un contrato padre o una plataforma..
        /// </summary>
        public static string MissingPlatformOrParentTenant
        {
            get
            {
                return ResourceManager.GetString("MissingPlatformOrParentTenant", resourceCulture);
            }
        }

        /// <summary>
        /// Plataforma es requerida. No se ha configurado la plataforma por defecto de Facture. El contrato debería tener un contrato padre o una plataforma...
        /// </summary>
        public static string MissingPlatformOrParentTenantConfig
        {
            get
            {
                return ResourceManager.GetString("MissingPlatformOrParentTenantConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La confirmación de la contraseña es requerida..
        /// </summary>
        public static string MustConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("MustConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña debe ser diferente a la existente..
        /// </summary>
        public static string NewPassswordMustBeDifferent
        {
            get
            {
                return ResourceManager.GetString("NewPassswordMustBeDifferent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contrato padre no se puede inactivar porque tiene hijos..
        /// </summary>
        public static string ParentTenantHasChildrenAndCannotBeInactive
        {
            get
            {
                return ResourceManager.GetString("ParentTenantHasChildrenAndCannotBeInactive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El contrato padre &apos;{0}&apos; no existe..
        /// </summary>
        public static string ParentTenantNotFound
        {
            get
            {
                return ResourceManager.GetString("ParentTenantNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La contraseña ha expirado. Una nueva contraseña debe ser asignada..
        /// </summary>
        public static string PasswordIsExpired
        {
            get
            {
                return ResourceManager.GetString("PasswordIsExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La nueva contraseña ya ha sido utilizada..
        /// </summary>
        public static string PasswordIsInHistory
        {
            get
            {
                return ResourceManager.GetString("PasswordIsInHistory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La contraseña no puede ser nula..
        /// </summary>
        public static string PasswordNotNull
        {
            get
            {
                return ResourceManager.GetString("PasswordNotNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas deben tener al menos 8 dígitos, para mayor seguridad utilice letras, números y caracteres especiales..
        /// </summary>
        public static string PasswordNotStrong
        {
            get
            {
                return ResourceManager.GetString("PasswordNotStrong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permissions not found..
        /// </summary>
        public static string PermissionsNotFound
        {
            get
            {
                return ResourceManager.GetString("PermissionsNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El registro ya existe. Nombre: &apos;{0}&apos;..
        /// </summary>
        public static string RecordAlreadyFoundWithName
        {
            get
            {
                return ResourceManager.GetString("RecordAlreadyFoundWithName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El registro no está activo..
        /// </summary>
        public static string RecordNotActive
        {
            get
            {
                return ResourceManager.GetString("RecordNotActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registro no existe. Key: &apos;{0}&apos;..
        /// </summary>
        public static string RecordNotFoundWithKey
        {
            get
            {
                return ResourceManager.GetString("RecordNotFoundWithKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol &apos;{0}&apos; ya existe en el Tenant Id &apos;{1}&apos;.
        /// </summary>
        public static string RoleAlreadyOnTenant
        {
            get
            {
                return ResourceManager.GetString("RoleAlreadyOnTenant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol &apos;{0}&apos; no existe..
        /// </summary>
        public static string RoleDoesNotExist
        {
            get
            {
                return ResourceManager.GetString("RoleDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El rol no soporte grupos anidados..
        /// </summary>
        public static string RoleDoesNotSupportGroupNesting
        {
            get
            {
                return ResourceManager.GetString("RoleDoesNotSupportGroupNesting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El contrato &apos;{0}&apos; ya existe..
        /// </summary>
        public static string TenantAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("TenantAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El TenantId es requerido..
        /// </summary>
        public static string TenantIdRequired
        {
            get
            {
                return ResourceManager.GetString("TenantIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El TenantId es requerido porque el usuario tiene multiple contratos asociados..
        /// </summary>
        public static string TenantIdRequiredWhenMultipleFound
        {
            get
            {
                return ResourceManager.GetString("TenantIdRequiredWhenMultipleFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El contrato &apos;{0}&apos; no es un contrato padre..
        /// </summary>
        public static string TenantIsNotParent
        {
            get
            {
                return ResourceManager.GetString("TenantIsNotParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontró el contrato..
        /// </summary>
        public static string TenantNotFound
        {
            get
            {
                return ResourceManager.GetString("TenantNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contrato &apos;{0}&apos; no encontrado..
        /// </summary>
        public static string TenantNotNull
        {
            get
            {
                return ResourceManager.GetString("TenantNotNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La configuración del contrato &apos;{0}&apos; no existe..
        /// </summary>
        public static string TenantSettingNotFound
        {
            get
            {
                return ResourceManager.GetString("TenantSettingNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contrato a impersonar no existe..
        /// </summary>
        public static string TenantToImpersonateNotFound
        {
            get
            {
                return ResourceManager.GetString("TenantToImpersonateNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El token de seguridad no puede ser igual al token de seguridad anterior..
        /// </summary>
        public static string TokenAreEqual
        {
            get
            {
                return ResourceManager.GetString("TokenAreEqual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El token ha caducado..
        /// </summary>
        public static string TokenHasExpired
        {
            get
            {
                return ResourceManager.GetString("TokenHasExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El token debe ser diferente al último token..
        /// </summary>
        public static string TokenMustBeDifferentFromLast
        {
            get
            {
                return ResourceManager.GetString("TokenMustBeDifferentFromLast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El token no puede ser nulo..
        /// </summary>
        public static string TokenMustNotBeNull
        {
            get
            {
                return ResourceManager.GetString("TokenMustNotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clase UserIdentity recibida no es válida..
        /// </summary>
        public static string UnexpectdUserIdentity
        {
            get
            {
                return ResourceManager.GetString("UnexpectdUserIdentity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario &apos;{0}&apos; ya está asignado al rol &apos;{1}&apos;..
        /// </summary>
        public static string UserAlreadyAssignedToRole
        {
            get
            {
                return ResourceManager.GetString("UserAlreadyAssignedToRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario y la contraseña deben ser diferentes..
        /// </summary>
        public static string UserAndPasswordMustBeDifferent
        {
            get
            {
                return ResourceManager.GetString("UserAndPasswordMustBeDifferent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario &apos;{0}&apos; no existe..
        /// </summary>
        public static string UserDoesNotExist
        {
            get
            {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario no está habilitado..
        /// </summary>
        public static string UserIsNotEnabled
        {
            get
            {
                return ResourceManager.GetString("UserIsNotEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario &apos;{0}&apos; no existe..
        /// </summary>
        public static string UsernameNotExists
        {
            get
            {
                return ResourceManager.GetString("UsernameNotExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario no puede ser nulo..
        /// </summary>
        public static string UsernameNotNull
        {
            get
            {
                return ResourceManager.GetString("UsernameNotNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario &apos;{0}&apos; NO está asignado al rol &apos;{1}&apos;..
        /// </summary>
        public static string UserNotAssignedToRole
        {
            get
            {
                return ResourceManager.GetString("UserNotAssignedToRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La contraseña es débil..
        /// </summary>
        public static string WeakPassword
        {
            get
            {
                return ResourceManager.GetString("WeakPassword", resourceCulture);
            }
        }
        public static string CannotConvertToNumber
        {
            get
            {
                return ResourceManager.GetString("CannotConvertToNumber", resourceCulture);
            }
        }
    }
}
